#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright (c) 2018-2020 Robert Haines.
#
# Licensed under the BSD License. See LICENCE for details.

require 'rubygems'
require 'bundler/setup'

require_relative 'lib/mod_player/options'
require_relative 'lib/mod_player/player'

options = ModPlayer::Options.read_opts(ARGV)

saved_err = STDERR.dup
STDERR.reopen(File.new('/dev/null', 'w'))

player = ModPlayer::Player.new(options)

at_exit do
  STDERR.reopen(saved_err)
  player.stop
end

player.play
